home:
  description: Emberは複数のRSSフィードをまとめて記事をタイムライン形式で表示します
users:
  - name: AIsmiley
    joined_at:
      year: 2025
      month: 5
    left_at: null
    tags:
      - News
    sources:
      - https://aismiley.co.jp/ai_news/feed/
  - name: note
    joined_at:
      year: 2025
      month: 5
    left_at: null
    tags:
      - News
    sources:
      - https://note.com/hashtag/AI%E3%83%8B%E3%83%A5%E3%83%BC%E3%82%B9/rss
  - name: OpenAI
    joined_at:
      year: 2025
      month: 5
    left_at: null
    tags:
      - 1st Party
    sources:
      - https://openai.com/news/rss.xml
  - name: Gemini
    joined_at:
      year: 2025
      month: 5
    left_at: null
    tags:
      - 1st Party
    sources:
      - https://blog.google/products/gemini/rss/